# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: loans-deployment
serviceName: loans
appLabel: loans
appName: loans

replicaCount: 1

image:
  repository: joheiss/sb3-loans
  tag: v6

containerPort: 8092

service:
  type: ClusterIP
  port: 8092
  targetPort: 8092

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false

mysql_enabled: true
mysqlUrl: "jdbc:mysql://loansdb-mysql.default.svc.cluster.local:3307/loansdb"
