apiVersion: apps/v1
kind: Deployment
metadata:
  name: loans-db-deployment
  labels:
    app: loansdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loansdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: loansdb
    spec:
      containers:
      - name: loansdb
        image: mysql
        ports:
          - containerPort: 3306
        resources:
          limits:
            memory: 512Mi
            cpu: 1
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: jovisco-configmap
              key: LOANS_DB
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            configMapKeyRef:
              name: jovisco-configmap
              key: MYSQL_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: loansdb
spec:
  selector:
    app: loansdb
  ports:
    - protocol: TCP
      port: 3307
      targetPort: 3306