global:
  configMapName: joviscodev-configmap
  activeProfile: default
  configServerURL: configserver:http://configserver:8071/
  eurekaServerURL: http://eurekaserver:8070/eureka/
  keyCloakURL: http://keycloak.default.svc.cluster.local:80/realms/master/protocol/openid-connect/certs
  openTelemetryJavaAgent: "-javaagent:/app/libs/opentelemetry-javaagent-1.32.0.jar"
  otelExporterEndPoint: http://tempo-grafana-tempo-distributor:4317
  otelMetricsExporter: none
  kafkaBrokerURL: kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9092
  mysqlRootPassword: root 
  accountsDbUrl: accountsdb-mysql.default.svc.cluster.local:3306
  loansDbUrl: loansdb-mysql.default.svc.cluster.local:3306
  cardsDbUrl: cardsdb-mysql.default.svc.cluster.local:3306
  rabbitMqUrl: rabbitmq.default.svc.cluster.local:5672
