apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards-db-deployment
  labels:
    app: cardsdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardsdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cardsdb
    spec:
      containers:
      - name: cardsdb
        image: mysql
        ports:
          - containerPort: 3306
        resources:
          limits:
            memory: 512Mi
            cpu: 1
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: jovisco-configmap
              key: CARDS_DB
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            configMapKeyRef:
              name: jovisco-configmap
              key: MYSQL_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: cardsdb
spec:
  selector:
    app: cardsdb
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3308
      targetPort: 3306