# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: cards-deployment
serviceName: cards
appLabel: cards
appName: cards

replicaCount: 1

image:
  repository: joheiss/sb3-cards
  tag: v6

containerPort: 8093

service:
  type: ClusterIP
  port: 8093
  targetPort: 8093

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false

mysql_enabled: true
mysqlUrl: "jdbc:mysql:/cardsdb-mysql.default.svc.cluster.local:3308/cardsdb"
