# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: accounts-deployment
serviceName: accounts
appLabel: accounts
appName: accounts

replicaCount: 1

image:
  repository: joheiss/sb3-accounts
  tag: v8.2

containerPort: 8091

service:
  type: ClusterIP
  port: 8091
  targetPort: 8091

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: true

mysql_enabled: true
mysqlUrl: "jdbc:mysql://accountsdb-mysql.default.svc.cluster.local:3306/accountsdb"
